//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class CierreCajaDetalleRow
    {
        public string Concepto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Observaciones { get; set; }
        public int Orden { get; set; }
    }
}
