//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.ComprasProductos = new HashSet<CompraProducto>();
        }
    
        public int CompraId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Numero { get; set; }
        public int FacturaId { get; set; }
        public int CuentaId { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public System.Guid Identifier { get; set; }
        public int MaxiKioscoId { get; set; }
        public decimal PercepcionIVA { get; set; }
        public decimal PercepcionDGR { get; set; }
        public decimal ImporteFactura { get; set; }
        public decimal TotalCompra { get; set; }
        public decimal Descuento { get; set; }
        public decimal ImporteFinal { get; set; }
        public string TipoComprobante { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual ICollection<CompraProducto> ComprasProductos { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual MaxiKiosco MaxiKiosco { get; set; }
    }
}
