//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ControlStockVistaPreviaRow
    {
        public Nullable<int> Fila { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> Diferencia { get; set; }
    }
}
