//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ControlStockObtenerDetalleRow
    {
        public Nullable<int> StockId { get; set; }
        public string Producto { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> StockActual { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public int Desincronizado { get; set; }
        public int Eliminado { get; set; }
        public Nullable<System.Guid> Identifier { get; set; }
        public int HabilitadoParaCorregir { get; set; }
    }
}
