//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlStock
    {
        public ControlStock()
        {
            this.ControlStockDetalles = new HashSet<ControlStockDetalle>();
            this.ControlStockDetalles1 = new HashSet<ControlStockDetalle>();
        }
    
        public int ControlStockId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public Nullable<int> RubroId { get; set; }
        public int MaxiKioscoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> NroControl { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Desincronizado { get; set; }
        public bool Eliminado { get; set; }
        public System.Guid Identifier { get; set; }
        public bool Cerrado { get; set; }
        public Nullable<System.DateTime> FechaCorreccion { get; set; }
        public bool MasVendidos { get; set; }
        public Nullable<int> CantidadFilas { get; set; }
        public int LimiteInferior { get; set; }
        public int LimiteSuperior { get; set; }
        public bool ConStockCero { get; set; }
    
        public virtual MaxiKiosco MaxiKiosco { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ControlStockDetalle> ControlStockDetalles { get; set; }
        public virtual ICollection<ControlStockDetalle> ControlStockDetalles1 { get; set; }
    }
}
