//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlStockDetalle
    {
        public int ControlStockDetalleId { get; set; }
        public int ControlStockId { get; set; }
        public int StockId { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Desincronizado { get; set; }
        public bool Eliminado { get; set; }
        public System.Guid Identifier { get; set; }
        public Nullable<decimal> Correccion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> MotivoCorreccionId { get; set; }
        public bool HabilitadoParaCorregir { get; set; }
        public Nullable<int> ControlStockPrevioId { get; set; }
    
        public virtual ControlStock ControlStock { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual MotivoCorreccion MotivoCorreccion { get; set; }
        public virtual ControlStock ControlStockPrevio { get; set; }
    }
}
