//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo
    {
        public int CostoId { get; set; }
        public Nullable<int> CierreCajaId { get; set; }
        public int CategoriaCostoId { get; set; }
        public string Observaciones { get; set; }
        public string NroComprobante { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Aprobado { get; set; }
        public System.Guid Identifier { get; set; }
        public bool Desincronizado { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> TurnoId { get; set; }
    
        public virtual CategoriaCosto CategoriaCosto { get; set; }
        public virtual CierreCaja CierreCaja { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
