//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcepcionRubro
    {
        public int ExcepcionRubroId { get; set; }
        public System.Guid Identifier { get; set; }
        public int RubroId { get; set; }
        public System.TimeSpan Desde { get; set; }
        public System.TimeSpan Hasta { get; set; }
        public Nullable<decimal> RecargoAbsoluto { get; set; }
        public Nullable<decimal> RecargoPorcentaje { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public bool Desincronizado { get; set; }
        public int MaxiKioscoId { get; set; }
    
        public virtual Rubro Rubro { get; set; }
        public virtual MaxiKiosco MaxiKiosco { get; set; }
    }
}
