//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importacion
    {
        public int ImportacionID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int MaxiKioscoID { get; set; }
        public string Nombre { get; set; }
        public int Secuencia { get; set; }
    
        public virtual MaxiKiosco MaxiKiosco { get; set; }
    }
}
