//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaxiKioscoTurno
    {
        public int MaxiKioscoTurnoId { get; set; }
        public int MaxiKioscoId { get; set; }
        public int TurnoId { get; set; }
        public Nullable<decimal> MontoMaximoVentaConTickets { get; set; }
        public bool Eliminado { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public System.Guid Identifier { get; set; }
    
        public virtual MaxiKiosco MaxiKiosco { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
