//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeTicketError
    {
        public int MensajeTicketErrorId { get; set; }
        public int TicketErrorId { get; set; }
        public string Texto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public bool EsDeAdmin { get; set; }
    
        public virtual TicketError TicketError { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
