//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoCorreccion
    {
        public MotivoCorreccion()
        {
            this.CorreccionStocks = new HashSet<CorreccionStock>();
            this.ControlStockDetalles = new HashSet<ControlStockDetalle>();
            this.Cuentas = new HashSet<Cuenta>();
        }
    
        public int MotivoCorreccionId { get; set; }
        public string Descripcion { get; set; }
        public bool SumarAStock { get; set; }
        public bool MostrarEnDropdown { get; set; }
    
        public virtual ICollection<CorreccionStock> CorreccionStocks { get; set; }
        public virtual ICollection<ControlStockDetalle> ControlStockDetalles { get; set; }
        public virtual ICollection<Cuenta> Cuentas { get; set; }
    }
}
