//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionCaja
    {
        public int OperacionCajaId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CierreCajaId { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> MotivoId { get; set; }
        public string Observaciones { get; set; }
        public bool Desincronizado { get; set; }
        public int UsuarioCreadorId { get; set; }
        public Nullable<int> UltimoUsuarioModificacionId { get; set; }
        public System.Guid Identifier { get; set; }
    
        public virtual CierreCaja CierreCaja { get; set; }
        public virtual MotivoOperacionCaja MotivoOperacionCaja { get; set; }
        public virtual Usuario UsuarioCreador { get; set; }
        public virtual Usuario UsuarioModificador { get; set; }
    }
}
