//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ProductoStock
    {
        public string MaxiKiosco { get; set; }
        public Nullable<decimal> StockActual { get; set; }
        public Nullable<decimal> Vendido { get; set; }
    }
}
