//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CodigosProductos = new HashSet<CodigoProducto>();
            this.VentaProductos = new HashSet<VentaProducto>();
            this.Stocks = new HashSet<Stock>();
            this.ComprasProductos = new HashSet<CompraProducto>();
            this.CorreccionStocks = new HashSet<CorreccionStock>();
            this.ProveedorProductos = new HashSet<ProveedorProducto>();
            this.TransferenciaProductos = new HashSet<TransferenciaProducto>();
            this.PromocionesPadres = new HashSet<ProductoPromocion>();
            this.PromocionesHijos = new HashSet<ProductoPromocion>();
            this.RetiroPersonalProductoes = new HashSet<RetiroPersonalProducto>();
        }
    
        public int ProductoId { get; set; }
        public System.Guid Identifier { get; set; }
        public int RubroId { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> StockReposicion { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public int CuentaId { get; set; }
        public bool AceptaCantidadesDecimales { get; set; }
        public decimal PrecioConIVA { get; set; }
        public decimal PrecioSinIVA { get; set; }
        public bool EsPromocion { get; set; }
        public bool DisponibleEnDeposito { get; set; }
        public Nullable<int> FactorAgrupamiento { get; set; }
    
        public virtual ICollection<CodigoProducto> CodigosProductos { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual ICollection<VentaProducto> VentaProductos { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<CompraProducto> ComprasProductos { get; set; }
        public virtual ICollection<CorreccionStock> CorreccionStocks { get; set; }
        public virtual ICollection<ProveedorProducto> ProveedorProductos { get; set; }
        public virtual ICollection<TransferenciaProducto> TransferenciaProductos { get; set; }
        public virtual ICollection<ProductoPromocion> PromocionesPadres { get; set; }
        public virtual ICollection<ProductoPromocion> PromocionesHijos { get; set; }
        public virtual ICollection<RetiroPersonalProducto> RetiroPersonalProductoes { get; set; }
    }
}
