//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ProductoParaTransferencia
    {
        public int ProductoId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public bool AceptaCantidadesDecimales { get; set; }
        public string Marca { get; set; }
        public decimal StockOrigen { get; set; }
        public decimal StockDestino { get; set; }
        public decimal PrecioSinIVA { get; set; }
        public decimal PrecioConIVA { get; set; }
        public decimal CostoConIVA { get; set; }
    }
}
