//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ProductoExportacion
    {
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Rubro { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> StockReposicion { get; set; }
        public decimal PrecioSinIVA { get; set; }
        public decimal PrecioConIVA { get; set; }
        public string DisponibleEnDeposito { get; set; }
    }
}
