//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class PromocionCompleta
    {
        public System.Guid Identifier { get; set; }
        public string CodigosListado { get; set; }
        public string Descripcion { get; set; }
        public string CostosResumen { get; set; }
        public decimal PrecioConIVA { get; set; }
        public int ProductoId { get; set; }
    }
}
