//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Facturas = new HashSet<Factura>();
            this.UsuarioProveedores = new HashSet<UsuarioProveedor>();
            this.ProveedorProductoes = new HashSet<ProveedorProducto>();
            this.ControlesStock = new HashSet<ControlStock>();
        }
    
        public int ProveedorId { get; set; }
        public System.Guid Identifier { get; set; }
        public string Nombre { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<int> TipoCuitId { get; set; }
        public string CuitNro { get; set; }
        public string Email { get; set; }
        public string PaginaWeb { get; set; }
        public string Observaciones { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public int CuentaId { get; set; }
        public Nullable<decimal> PercepcionDGR { get; set; }
        public bool AplicaPercepcionIVA { get; set; }
        public bool NoReflejarFacturaEnCaja { get; set; }
        public string TipoComprobante { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual TipoCuit TipoCuit { get; set; }
        public virtual ICollection<UsuarioProveedor> UsuarioProveedores { get; set; }
        public virtual ICollection<ProveedorProducto> ProveedorProductoes { get; set; }
        public virtual ICollection<ControlStock> ControlesStock { get; set; }
    }
}
