//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuentoBillete
    {
        public int RecuentoBilleteId { get; set; }
        public int CierreCajaId { get; set; }
        public int BilleteId { get; set; }
        public int Cantidad { get; set; }
        public System.Guid Identifier { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Billete Billete { get; set; }
        public virtual CierreCaja CierreCaja { get; set; }
    }
}
