//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteRol
    {
        public int ReporteRoleId { get; set; }
        public int RoleId { get; set; }
        public int ReporteId { get; set; }
        public bool Desincronizado { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public System.Guid Identifier { get; set; }
    
        public virtual Reporte Reporte { get; set; }
        public virtual Role Roles { get; set; }
    }
}
