//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteStock
    {
        public int ReporteStockId { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] Valorizado { get; set; }
        public byte[] ValorizadoGeneral { get; set; }
        public byte[] ValorizadoDetallado { get; set; }
        public byte[] ValorizadoDetalladoGeneral { get; set; }
    }
}
