//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class ReponerStock
    {
        public string Producto { get; set; }
        public string Proveedor { get; set; }
        public decimal StockActual { get; set; }
        public Nullable<int> StockReposicion { get; set; }
        public string Maxikiosco { get; set; }
    }
}
