//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetiroPersonalProducto
    {
        public int RetiroPersonalProductoId { get; set; }
        public System.Guid Identifier { get; set; }
        public int RetiroPersonalId { get; set; }
        public int ProductoId { get; set; }
        public decimal Costo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<decimal> AdicionalPorExcepcion { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual RetiroPersonal RetiroPersonal { get; set; }
    }
}
