//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptCierreDeCaja
    {
        public string MaxiKioscoNombre { get; set; }
        public string MaxiKioscoDireccion { get; set; }
        public string UsuarioNombre { get; set; }
        public string UsuarioApellido { get; set; }
        public Nullable<int> CantPorDebajoEsperado { get; set; }
        public Nullable<int> CantPorEncimaEsperado { get; set; }
    }
}
