//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptComprasPorProveedor
    {
        public string Proveedor { get; set; }
        public Nullable<decimal> DescuentoTotal { get; set; }
        public Nullable<decimal> DRG { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public decimal ImportaA { get; set; }
        public decimal ImporteX { get; set; }
    }
}
