//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptGastosPorCategoria
    {
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
        public string MaxiKiosco { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal ImporteTotal { get; set; }
        public string Observaciones { get; set; }
        public string NroComprobante { get; set; }
    }
}
