//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptProductosEnDeposito
    {
        public string Codigo { get; set; }
        public string Rubro { get; set; }
        public string Producto { get; set; }
        public string Marca { get; set; }
    }
}
