//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptRetirosPersonalesRow
    {
        public System.DateTime Fecha { get; set; }
        public string NombreUsuario { get; set; }
        public decimal CostoTotal { get; set; }
        public decimal ImporteTotal { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
    }
}
