//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptStock
    {
        public string MaxiKiosco { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Monto { get; set; }
    }
}
