//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    
    public partial class RptVentasNegativasPorTicketRow
    {
        public int Ticket { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string Producto { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public decimal CostoUnitario { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public string Usuario { get; set; }
    }
}
