//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.ExcepcionRubros = new HashSet<ExcepcionRubro>();
            this.Productos = new HashSet<Producto>();
            this.ControlesStock = new HashSet<ControlStock>();
        }
    
        public int RubroId { get; set; }
        public System.Guid Identifier { get; set; }
        public string Descripcion { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public int CuentaId { get; set; }
        public bool NoFacturar { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<ExcepcionRubro> ExcepcionRubros { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
        public virtual ICollection<ControlStock> ControlesStock { get; set; }
    }
}
