//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.StockTransacciones = new HashSet<StockTransaccion>();
            this.ControlStockDetalles = new HashSet<ControlStockDetalle>();
        }
    
        public int StockId { get; set; }
        public int ProductoId { get; set; }
        public int MaxiKioscoId { get; set; }
        public System.Guid Identifier { get; set; }
        public decimal StockActual { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public string OperacionCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual MaxiKiosco MaxiKiosco { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<StockTransaccion> StockTransacciones { get; set; }
        public virtual ICollection<ControlStockDetalle> ControlStockDetalles { get; set; }
    }
}
