//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransaccion
    {
        public int StockTransaccionId { get; set; }
        public int StockId { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public System.Guid Identifier { get; set; }
        public decimal Cantidad { get; set; }
        public int StockTransaccionTipoId { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual StockTransaccionTipo StockTransaccionTipo { get; set; }
    }
}
