//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncMaxiKiosco
    {
        public System.Guid Identifier { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> UltimaSecuenciaExportacion { get; set; }
        public Nullable<int> UltimaSecuenciaAcusada { get; set; }
        public Nullable<System.DateTime> UltimaSincronizacionExitosa { get; set; }
        public Nullable<System.DateTime> UltimaConexion { get; set; }
    }
}
