//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketError
    {
        public TicketError()
        {
            this.MensajeTicketErrores = new HashSet<MensajeTicketError>();
        }
    
        public int TicketErrorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public OrigenTicketEnum Origen { get; set; }
        public string Mensaje { get; set; }
        public EstadoTicketEnum EstadoTicketId { get; set; }
        public Nullable<System.DateTime> FechaEnProgreso { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Email { get; set; }
        public string Titulo { get; set; }
    
        public virtual EstadoTicket EstadoTicket { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<MensajeTicketError> MensajeTicketErrores { get; set; }
    }
}
