//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCuit
    {
        public TipoCuit()
        {
            this.Proveedores = new HashSet<Proveedor>();
        }
    
        public int TipoCuitId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public bool Desincronizado { get; set; }
    
        public virtual ICollection<Proveedor> Proveedores { get; set; }
    }
}
