//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public Turno()
        {
            this.MaxiKioscoTurnos = new HashSet<MaxiKioscoTurno>();
        }
    
        public int TurnoId { get; set; }
        public string Descripcion { get; set; }
        public System.TimeSpan Desde { get; set; }
        public System.TimeSpan Hasta { get; set; }
    
        public virtual ICollection<MaxiKioscoTurno> MaxiKioscoTurnos { get; set; }
    }
}
