//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Roles = new HashSet<Role>();
            this.Exportacions = new HashSet<Exportacion>();
            this.UsuarioProveedores = new HashSet<UsuarioProveedor>();
            this.CierreCajas = new HashSet<CierreCaja>();
            this.OperacionCajasCreadas = new HashSet<OperacionCaja>();
            this.OperacionCajasModificadas = new HashSet<OperacionCaja>();
            this.TicketErrors = new HashSet<TicketError>();
            this.MensajeTicketErrors = new HashSet<MensajeTicketError>();
            this.ControleStock = new HashSet<ControlStock>();
            this.Facturas = new HashSet<Factura>();
            this.Transferencias = new HashSet<Transferencia>();
            this.Costoes = new HashSet<Costo>();
        }
    
        public int UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public int CuentaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.Guid Identifier { get; set; }
        public bool Desincronizado { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Exportacion> Exportacions { get; set; }
        public virtual ICollection<UsuarioProveedor> UsuarioProveedores { get; set; }
        public virtual ICollection<CierreCaja> CierreCajas { get; set; }
        public virtual ICollection<OperacionCaja> OperacionCajasCreadas { get; set; }
        public virtual ICollection<OperacionCaja> OperacionCajasModificadas { get; set; }
        public virtual ICollection<TicketError> TicketErrors { get; set; }
        public virtual ICollection<MensajeTicketError> MensajeTicketErrors { get; set; }
        public virtual ICollection<ControlStock> ControleStock { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual ICollection<Transferencia> Transferencias { get; set; }
        public virtual ICollection<Costo> Costoes { get; set; }
    }
}
