//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.VentaProductos = new HashSet<VentaProducto>();
        }
    
        public int VentaId { get; set; }
        public System.Guid Identifier { get; set; }
        public int CierreCajaId { get; set; }
        public decimal ImporteTotal { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public bool Eliminado { get; set; }
        public bool Desincronizado { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public decimal CostoTotal { get; set; }
    
        public virtual ICollection<VentaProducto> VentaProductos { get; set; }
        public virtual CierreCaja CierreCaja { get; set; }
    }
}
