//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Web.ForzarSincronizacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatosResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaxiKioscos.Web.ForzarSincronizacionService.ExportacionData[] ExportacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaxiKioscos.Web.ForzarSincronizacionService.ExportacionData[] Exportaciones {
            get {
                return this.ExportacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportacionesField, value) != true)) {
                    this.ExportacionesField = value;
                    this.RaisePropertyChanged("Exportaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportacionData", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ExportacionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForzarSincronizacionService.IForzarSincronizacionService")]
    public interface IForzarSincronizacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForzarSincronizacionService/Sincronizar", ReplyAction="http://tempuri.org/IForzarSincronizacionService/SincronizarResponse")]
        MaxiKioscos.Web.ForzarSincronizacionService.ObtenerDatosResponse Sincronizar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForzarSincronizacionService/Sincronizar", ReplyAction="http://tempuri.org/IForzarSincronizacionService/SincronizarResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Web.ForzarSincronizacionService.ObtenerDatosResponse> SincronizarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForzarSincronizacionServiceChannel : MaxiKioscos.Web.ForzarSincronizacionService.IForzarSincronizacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForzarSincronizacionServiceClient : System.ServiceModel.ClientBase<MaxiKioscos.Web.ForzarSincronizacionService.IForzarSincronizacionService>, MaxiKioscos.Web.ForzarSincronizacionService.IForzarSincronizacionService {
        
        public ForzarSincronizacionServiceClient() {
        }
        
        public ForzarSincronizacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForzarSincronizacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForzarSincronizacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForzarSincronizacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MaxiKioscos.Web.ForzarSincronizacionService.ObtenerDatosResponse Sincronizar() {
            return base.Channel.Sincronizar();
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Web.ForzarSincronizacionService.ObtenerDatosResponse> SincronizarAsync() {
            return base.Channel.SincronizarAsync();
        }
    }
}
