INSERT INTO [Reporte] VALUES ('Ventas por Cierre de Caja', 'Por Cierre de Caja','Ventas','/Reportes/VentasPorCierreCaja')
INSERT INTO [Reporte] VALUES ('Ventas por Ticket', 'Por Ticket','Ventas','/Reportes/VentasPorTicket')
INSERT INTO [Reporte] VALUES ('Ventas por Maxikiosco', 'Por Maxikiosco','Ventas','/Reportes/VentasPorMaxikioscos')
INSERT INTO [Reporte] VALUES ('Ventas por Producto', 'Por Producto','Ventas','/Reportes/VentasPorProductos')
INSERT INTO [Reporte] VALUES ('Venas Negativas por Ticket', 'Negativas por Ticket','Ventas','/Reportes/VentasNegativasPorTicket')
INSERT INTO [Reporte] VALUES ('Cierre de Caja General', 'General','Cierres de Caja','/Reportes/CierresDeCaja')
INSERT INTO [Reporte] VALUES ('Cierre de Caja Detalle', 'Detalle','Cierres de Caja','/Reportes/CierresDeCajaDetalle')
INSERT INTO [Reporte] VALUES ('Stock General', 'Stock General','Stock','/Reportes/Stock')
INSERT INTO [Reporte] VALUES ('Productos para reponer', 'Productos para reponer','Stock','/Reportes/ProductosParaReponer')
INSERT INTO [Reporte] VALUES ('Stock Valorizado', 'Valorizado','Stock','/Reportes/StockValorizado')
INSERT INTO [Reporte] VALUES ('Stock Valorizado Detallado', 'Valorizado Detallado','Stock','/Reportes/StockValorizadoDetallado')
INSERT INTO [Reporte] VALUES ('Transferencia por Producto', 'Transferencia por Producto','Stock','/Reportes/TransferenciasPorProducto')
INSERT INTO [Reporte] VALUES ('Retiros Personales General', 'General','Retiros Personales','/Reportes/RetirosPersonales')
INSERT INTO [Reporte] VALUES ('Retiros Personales por Ticket', 'Por Ticket','Retiros Personales','/Reportes/RetirosPersonalesPorTicket')
INSERT INTO [Reporte] VALUES ('Compras por Proveedor', 'Compras por Proveedor','Indicadores Especiales','/Reportes/ComprasPorProveedor')
INSERT INTO [Reporte] VALUES ('Dinero Actual en Caja', 'Dinero Actual en Caja','Indicadores Especiales','/Reportes/DineroPorMaxikiosco')
INSERT INTO [Reporte] VALUES ('Dinero Sobrante/Faltante', 'Dinero Sobrante/Faltante','Indicadores Especiales','/Reportes/DineroSobranteFaltante')
INSERT INTO [Reporte] VALUES ('Ganacia Adicional por Excepciones en Rubros', 'Ganacia Adicional por Excepciones en Rubros','Indicadores Especiales','/Reportes/GanaciaAdicionalExcepcionRubro')
INSERT INTO [Reporte] VALUES ('Auditoría de Productos', 'Productos','Auditoría','/Reportes/AuditoriaProductos')

