//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Winforms.SincronizationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosRequest", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatosRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MaxiKioscoIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UltimaSecuenciaExportacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UsuarioIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MaxiKioscoIdentifier {
            get {
                return this.MaxiKioscoIdentifierField;
            }
            set {
                if ((this.MaxiKioscoIdentifierField.Equals(value) != true)) {
                    this.MaxiKioscoIdentifierField = value;
                    this.RaisePropertyChanged("MaxiKioscoIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UltimaSecuenciaExportacion {
            get {
                return this.UltimaSecuenciaExportacionField;
            }
            set {
                if ((this.UltimaSecuenciaExportacionField.Equals(value) != true)) {
                    this.UltimaSecuenciaExportacionField = value;
                    this.RaisePropertyChanged("UltimaSecuenciaExportacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UsuarioIdentifier {
            get {
                return this.UsuarioIdentifierField;
            }
            set {
                if ((this.UsuarioIdentifierField.Equals(value) != true)) {
                    this.UsuarioIdentifierField = value;
                    this.RaisePropertyChanged("UsuarioIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatosResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaxiKioscos.Winforms.SincronizationService.ExportacionData[] ExportacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaxiKioscos.Winforms.SincronizationService.ExportacionData[] Exportaciones {
            get {
                return this.ExportacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportacionesField, value) != true)) {
                    this.ExportacionesField = value;
                    this.RaisePropertyChanged("Exportaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportacionData", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ExportacionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Secuencia {
            get {
                return this.SecuenciaField;
            }
            set {
                if ((this.SecuenciaField.Equals(value) != true)) {
                    this.SecuenciaField = value;
                    this.RaisePropertyChanged("Secuencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerDatosSecuencialResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ObtenerDatosSecuencialResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArchivosRestantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaxiKioscos.Winforms.SincronizationService.ExportacionData ExportacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchivosRestantes {
            get {
                return this.ArchivosRestantesField;
            }
            set {
                if ((this.ArchivosRestantesField.Equals(value) != true)) {
                    this.ArchivosRestantesField = value;
                    this.RaisePropertyChanged("ArchivosRestantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaxiKioscos.Winforms.SincronizationService.ExportacionData Exportacion {
            get {
                return this.ExportacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportacionField, value) != true)) {
                    this.ExportacionField = value;
                    this.RaisePropertyChanged("Exportacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatosRequest", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ActualizarDatosRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaxiKioscos.Winforms.SincronizationService.ExportacionData[] ExportacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MaxiKioscoIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaxiKioscos.Winforms.SincronizationService.ExportacionData[] Exportaciones {
            get {
                return this.ExportacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportacionesField, value) != true)) {
                    this.ExportacionesField = value;
                    this.RaisePropertyChanged("Exportaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MaxiKioscoIdentifier {
            get {
                return this.MaxiKioscoIdentifierField;
            }
            set {
                if ((this.MaxiKioscoIdentifierField.Equals(value) != true)) {
                    this.MaxiKioscoIdentifierField = value;
                    this.RaisePropertyChanged("MaxiKioscoIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarDatosResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ActualizarDatosResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensageErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UltimaSecuenciaExitosaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensageError {
            get {
                return this.MensageErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensageErrorField, value) != true)) {
                    this.MensageErrorField = value;
                    this.RaisePropertyChanged("MensageError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UltimaSecuenciaExitosa {
            get {
                return this.UltimaSecuenciaExitosaField;
            }
            set {
                if ((this.UltimaSecuenciaExitosaField.Equals(value) != true)) {
                    this.UltimaSecuenciaExitosaField = value;
                    this.RaisePropertyChanged("UltimaSecuenciaExitosa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcusarExportacionRequest", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class AcusarExportacionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraLocalISOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MaxiKioscoIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UltimaSecuenciaExportacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraLocalISO {
            get {
                return this.HoraLocalISOField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraLocalISOField, value) != true)) {
                    this.HoraLocalISOField = value;
                    this.RaisePropertyChanged("HoraLocalISO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MaxiKioscoIdentifier {
            get {
                return this.MaxiKioscoIdentifierField;
            }
            set {
                if ((this.MaxiKioscoIdentifierField.Equals(value) != true)) {
                    this.MaxiKioscoIdentifierField = value;
                    this.RaisePropertyChanged("MaxiKioscoIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UltimaSecuenciaExportacion {
            get {
                return this.UltimaSecuenciaExportacionField;
            }
            set {
                if ((this.UltimaSecuenciaExportacionField.Equals(value) != true)) {
                    this.UltimaSecuenciaExportacionField = value;
                    this.RaisePropertyChanged("UltimaSecuenciaExportacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InicializarKioscoResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class InicializarKioscoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaxiKioscos.Winforms.SincronizationService.MaxiKioscoData[] KioscosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaxiKioscos.Winforms.SincronizationService.MaxiKioscoData[] Kioscos {
            get {
                return this.KioscosField;
            }
            set {
                if ((object.ReferenceEquals(this.KioscosField, value) != true)) {
                    this.KioscosField = value;
                    this.RaisePropertyChanged("Kioscos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaxiKioscoData", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class MaxiKioscoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Asignado {
            get {
                return this.AsignadoField;
            }
            set {
                if ((this.AsignadoField.Equals(value) != true)) {
                    this.AsignadoField = value;
                    this.RaisePropertyChanged("Asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KioscoAsignadoResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class KioscoAsignadoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbreviacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abreviacion {
            get {
                return this.AbreviacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AbreviacionField, value) != true)) {
                    this.AbreviacionField = value;
                    this.RaisePropertyChanged("Abreviacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((this.IdentifierField.Equals(value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerSecuenciasResponse", Namespace="http://schemas.datacontract.org/2004/07/MaxiKioscos.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ObtenerSecuenciasResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UltimaSecuenciaAcusadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UltimaSecuenciaExportacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UltimaSecuenciaAcusada {
            get {
                return this.UltimaSecuenciaAcusadaField;
            }
            set {
                if ((this.UltimaSecuenciaAcusadaField.Equals(value) != true)) {
                    this.UltimaSecuenciaAcusadaField = value;
                    this.RaisePropertyChanged("UltimaSecuenciaAcusada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UltimaSecuenciaExportacion {
            get {
                return this.UltimaSecuenciaExportacionField;
            }
            set {
                if ((this.UltimaSecuenciaExportacionField.Equals(value) != true)) {
                    this.UltimaSecuenciaExportacionField = value;
                    this.RaisePropertyChanged("UltimaSecuenciaExportacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SincronizationService.ISincronizacionService")]
    public interface ISincronizacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerDatos", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerDatosResponse")]
        MaxiKioscos.Winforms.SincronizationService.ObtenerDatosResponse ObtenerDatos(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerDatos", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerDatosResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerDatosResponse> ObtenerDatosAsync(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerDatosSecuencial", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerDatosSecuencialResponse")]
        MaxiKioscos.Winforms.SincronizationService.ObtenerDatosSecuencialResponse ObtenerDatosSecuencial(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerDatosSecuencial", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerDatosSecuencialResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerDatosSecuencialResponse> ObtenerDatosSecuencialAsync(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ActualizarDatos", ReplyAction="http://tempuri.org/ISincronizacionService/ActualizarDatosResponse")]
        MaxiKioscos.Winforms.SincronizationService.ActualizarDatosResponse ActualizarDatos(MaxiKioscos.Winforms.SincronizationService.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ActualizarDatos", ReplyAction="http://tempuri.org/ISincronizacionService/ActualizarDatosResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ActualizarDatosResponse> ActualizarDatosAsync(MaxiKioscos.Winforms.SincronizationService.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/AcusarExportacion", ReplyAction="http://tempuri.org/ISincronizacionService/AcusarExportacionResponse")]
        void AcusarExportacion(MaxiKioscos.Winforms.SincronizationService.AcusarExportacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/AcusarExportacion", ReplyAction="http://tempuri.org/ISincronizacionService/AcusarExportacionResponse")]
        System.Threading.Tasks.Task AcusarExportacionAsync(MaxiKioscos.Winforms.SincronizationService.AcusarExportacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/InicializarKiosco", ReplyAction="http://tempuri.org/ISincronizacionService/InicializarKioscoResponse")]
        MaxiKioscos.Winforms.SincronizationService.InicializarKioscoResponse InicializarKiosco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/InicializarKiosco", ReplyAction="http://tempuri.org/ISincronizacionService/InicializarKioscoResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.InicializarKioscoResponse> InicializarKioscoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/MarcarKioscoComoAsignado", ReplyAction="http://tempuri.org/ISincronizacionService/MarcarKioscoComoAsignadoResponse")]
        MaxiKioscos.Winforms.SincronizationService.KioscoAsignadoResponse MarcarKioscoComoAsignado(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/MarcarKioscoComoAsignado", ReplyAction="http://tempuri.org/ISincronizacionService/MarcarKioscoComoAsignadoResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.KioscoAsignadoResponse> MarcarKioscoComoAsignadoAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerSecuencias", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerSecuenciasResponse")]
        MaxiKioscos.Winforms.SincronizationService.ObtenerSecuenciasResponse ObtenerSecuencias(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ObtenerSecuencias", ReplyAction="http://tempuri.org/ISincronizacionService/ObtenerSecuenciasResponse")]
        System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerSecuenciasResponse> ObtenerSecuenciasAsync(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ForzarArmadoDeArchivoExportacion", ReplyAction="http://tempuri.org/ISincronizacionService/ForzarArmadoDeArchivoExportacionRespons" +
            "e")]
        void ForzarArmadoDeArchivoExportacion(System.Guid usuarioIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISincronizacionService/ForzarArmadoDeArchivoExportacion", ReplyAction="http://tempuri.org/ISincronizacionService/ForzarArmadoDeArchivoExportacionRespons" +
            "e")]
        System.Threading.Tasks.Task ForzarArmadoDeArchivoExportacionAsync(System.Guid usuarioIdentifier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISincronizacionServiceChannel : MaxiKioscos.Winforms.SincronizationService.ISincronizacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SincronizacionServiceClient : System.ServiceModel.ClientBase<MaxiKioscos.Winforms.SincronizationService.ISincronizacionService>, MaxiKioscos.Winforms.SincronizationService.ISincronizacionService {
        
        public SincronizacionServiceClient() {
        }
        
        public SincronizacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SincronizacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SincronizacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MaxiKioscos.Winforms.SincronizationService.ObtenerDatosResponse ObtenerDatos(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerDatosResponse> ObtenerDatosAsync(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public MaxiKioscos.Winforms.SincronizationService.ObtenerDatosSecuencialResponse ObtenerDatosSecuencial(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosSecuencial(request);
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerDatosSecuencialResponse> ObtenerDatosSecuencialAsync(MaxiKioscos.Winforms.SincronizationService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosSecuencialAsync(request);
        }
        
        public MaxiKioscos.Winforms.SincronizationService.ActualizarDatosResponse ActualizarDatos(MaxiKioscos.Winforms.SincronizationService.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatos(request);
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ActualizarDatosResponse> ActualizarDatosAsync(MaxiKioscos.Winforms.SincronizationService.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatosAsync(request);
        }
        
        public void AcusarExportacion(MaxiKioscos.Winforms.SincronizationService.AcusarExportacionRequest request) {
            base.Channel.AcusarExportacion(request);
        }
        
        public System.Threading.Tasks.Task AcusarExportacionAsync(MaxiKioscos.Winforms.SincronizationService.AcusarExportacionRequest request) {
            return base.Channel.AcusarExportacionAsync(request);
        }
        
        public MaxiKioscos.Winforms.SincronizationService.InicializarKioscoResponse InicializarKiosco() {
            return base.Channel.InicializarKiosco();
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.InicializarKioscoResponse> InicializarKioscoAsync() {
            return base.Channel.InicializarKioscoAsync();
        }
        
        public MaxiKioscos.Winforms.SincronizationService.KioscoAsignadoResponse MarcarKioscoComoAsignado(string identifier) {
            return base.Channel.MarcarKioscoComoAsignado(identifier);
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.KioscoAsignadoResponse> MarcarKioscoComoAsignadoAsync(string identifier) {
            return base.Channel.MarcarKioscoComoAsignadoAsync(identifier);
        }
        
        public MaxiKioscos.Winforms.SincronizationService.ObtenerSecuenciasResponse ObtenerSecuencias(string identifier) {
            return base.Channel.ObtenerSecuencias(identifier);
        }
        
        public System.Threading.Tasks.Task<MaxiKioscos.Winforms.SincronizationService.ObtenerSecuenciasResponse> ObtenerSecuenciasAsync(string identifier) {
            return base.Channel.ObtenerSecuenciasAsync(identifier);
        }
        
        public void ForzarArmadoDeArchivoExportacion(System.Guid usuarioIdentifier) {
            base.Channel.ForzarArmadoDeArchivoExportacion(usuarioIdentifier);
        }
        
        public System.Threading.Tasks.Task ForzarArmadoDeArchivoExportacionAsync(System.Guid usuarioIdentifier) {
            return base.Channel.ForzarArmadoDeArchivoExportacionAsync(usuarioIdentifier);
        }
    }
}
