//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Winforms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaxiKioscos.Winforms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actualizar {
            get {
                object obj = ResourceManager.GetObject("actualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agregar {
            get {
                object obj = ResourceManager.GetObject("agregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AgregarGrupo {
            get {
                object obj = ResourceManager.GetObject("AgregarGrupo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AgregarUsuario {
            get {
                object obj = ResourceManager.GetObject("AgregarUsuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anterior {
            get {
                object obj = ResourceManager.GetObject("anterior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_folder {
            get {
                object obj = ResourceManager.GetObject("blue_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buscar {
            get {
                object obj = ResourceManager.GetObject("buscar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancelar {
            get {
                object obj = ResourceManager.GetObject("Cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cerrar {
            get {
                object obj = ResourceManager.GetObject("Cerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario cerrar la caja antes de cerrar la sesión.
        /// </summary>
        internal static string CerrarSesionConfirmacionCajaAbirta {
            get {
                return ResourceManager.GetString("CerrarSesionConfirmacionCajaAbirta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cierre de caja está presenta una diferencia con el total ingresado. Verifique Ingresos y Egresos..
        /// </summary>
        internal static string CierreCajaMensajeMargen {
            get {
                return ResourceManager.GetString("CierreCajaMensajeMargen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La compra se ha registrado correctamente.
        /// </summary>
        internal static string CompraExitosa {
            get {
                return ResourceManager.GetString("CompraExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conectado {
            get {
                object obj = ResourceManager.GetObject("conectado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap correcto {
            get {
                object obj = ResourceManager.GetObject("correcto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desconectado {
            get {
                object obj = ResourceManager.GetObject("desconectado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap detalle {
            get {
                object obj = ResourceManager.GetObject("detalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editdelete {
            get {
                object obj = ResourceManager.GetObject("editdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EliminarGrupo {
            get {
                object obj = ResourceManager.GetObject("EliminarGrupo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EliminarUsuario {
            get {
                object obj = ResourceManager.GetObject("EliminarUsuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar conectar el servicio para forzar la sincronización desde la web.
        /// </summary>
        internal static string ErrorAlConectarConServicioForzarSincronizacion {
            get {
                return ResourceManager.GetString("ErrorAlConectarConServicioForzarSincronizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conección para forzar la sincronización desde la web ya se encuentra establecida.
        /// </summary>
        internal static string ForzarSincronizacionConeccionEstablecida {
            get {
                return ResourceManager.GetString("ForzarSincronizacionConeccionEstablecida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap guardar {
            get {
                object obj = ResourceManager.GetObject("guardar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iDisk_Badge {
            get {
                object obj = ResourceManager.GetObject("iDisk_Badge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imprimir {
            get {
                object obj = ResourceManager.GetObject("imprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadingAzul {
            get {
                object obj = ResourceManager.GetObject("loadingAzul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Locked {
            get {
                object obj = ResourceManager.GetObject("Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Locked2 {
            get {
                object obj = ResourceManager.GetObject("Locked2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La última caja del usuario: {0} , no se cerró correctamente. ¿Desea cerrarla ahora?.
        /// </summary>
        internal static string MensajeCerrarCajaAnterior {
            get {
                return ResourceManager.GetString("MensajeCerrarCajaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ingresado no tiene los permisos necesarios.
        /// </summary>
        internal static string MensajeUsuarioSinPermisos {
            get {
                return ResourceManager.GetString("MensajeUsuarioSinPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modificar {
            get {
                object obj = ResourceManager.GetObject("modificar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PNG_dollar {
            get {
                object obj = ResourceManager.GetObject("PNG_dollar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap primero {
            get {
                object obj = ResourceManager.GetObject("primero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seguridad {
            get {
                object obj = ResourceManager.GetObject("seguridad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap siguiente {
            get {
                object obj = ResourceManager.GetObject("siguiente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea sincronizar los datos con las base de datos principal?.
        /// </summary>
        internal static string SincronizacionConfimacion {
            get {
                return ResourceManager.GetString("SincronizacionConfimacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro que desea actualizar los datos locales con los presentes en el archivo de sincronización.
        /// </summary>
        internal static string SincronizacionConfirmacionActualizarDesdeArchivo {
            get {
                return ResourceManager.GetString("SincronizacionConfirmacionActualizarDesdeArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrrido un error al sincronizar los datos por favor intente mas tarde.
        /// </summary>
        internal static string SincronizacionError {
            get {
                return ResourceManager.GetString("SincronizacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos han sido sincronizados correctamente.
        /// </summary>
        internal static string SincronizacionExitosa {
            get {
                return ResourceManager.GetString("SincronizacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronización.
        /// </summary>
        internal static string SincronizacionTitulo {
            get {
                return ResourceManager.GetString("SincronizacionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string TextoAceptar {
            get {
                return ResourceManager.GetString("TextoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string TextoCancelar {
            get {
                return ResourceManager.GetString("TextoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ultimo {
            get {
                object obj = ResourceManager.GetObject("ultimo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon user_group {
            get {
                object obj = ResourceManager.GetObject("user_group", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
