//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxiKioscos.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SincronizacionEntities : DbContext
    {
        public SincronizacionEntities()
            : base("name=SincronizacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SyncExportacion> SyncExportaciones { get; set; }
        public virtual DbSet<SyncMaxiKiosco> SyncMaxiKioscos { get; set; }
        public virtual DbSet<SyncExportacionArchivo> SyncExportacionArchivos { get; set; }
    }
}
